enc_list
enc_import --avro_files pprl-scaling-framework-shell/target/appassembler/data/dblp/fbf_30_2_author_title/avro --schema_file pprl-scaling-framework-shell/target/appassembler/data/dblp/fbf_30_2_author_title/schema/fbf_30_2_author_title.avsc --method FBF --name orphan_enc
enc_import --avro_files pprl-scaling-framework-shell/target/appassembler/data/dblp/fbf_30_2_author_title/avro --schema_file pprl-scaling-framework-shell/target/appassembler/data/dblp/fbf_30_2_author_title/schema/fbf_30_2_author_title.avsc --method FBF --name non_orphan_enc --dataset dblp
enc_import --avro_files pprl-scaling-framework-shell/target/appassembler/data/dblp/fbf_30_2_author_title/avro --schema_file pprl-scaling-framework-shell/target/appassembler/data/dblp/fbf_30_2_author_title/schema/fbf_30_2_author_title.avsc --method FBF --dataset dblp
enc_list
enc_drop_all --delete_files YES
enc_import --avro_files pprl-scaling-framework-shell/target/appassembler/data/dblp/fbf_30_2_author_title/avro --schema_file pprl-scaling-framework-shell/target/appassembler/data/dblp/fbf_30_2_author_title/schema/fbf_30_2_author_title.avsc --method FBF --dataset dblp
enc_import --avro_files pprl-scaling-framework-shell/target/appassembler/data/dblp/fbf_500_30_2_author_title/avro --schema_file pprl-scaling-framework-shell/target/appassembler/data/dblp/fbf_500_30_2_author_title/schema/fbf_500_30_2_author_title.avsc --method FBF --dataset dblp
enc_import --avro_files pprl-scaling-framework-shell/target/appassembler/data/dblp/fbf_1024_30_2_author_title/avro --schema_file pprl-scaling-framework-shell/target/appassembler/data/dblp/fbf_1024_30_2_author_title/schema/fbf_1024_30_2_author_title.avsc --method FBF --dataset dblp
enc_import --avro_files pprl-scaling-framework-shell/target/appassembler/data/dblp/rbf_30_2_author_title/avro --schema_file pprl-scaling-framework-shell/target/appassembler/data/dblp/rbf_30_2_author_title/schema/rbf_30_2_author_title.avsc --method RBF --dataset dblp
enc_import --avro_files pprl-scaling-framework-shell/target/appassembler/data/dblp/rbf_500_30_2_author_title/avro --schema_file pprl-scaling-framework-shell/target/appassembler/data/dblp/rbf_500_30_2_author_title/schema/rbf_500_30_2_author_title.avsc --method RBF --dataset dblp
enc_import --avro_files pprl-scaling-framework-shell/target/appassembler/data/dblp/rbf_1024_30_2_author_title/avro --schema_file pprl-scaling-framework-shell/target/appassembler/data/dblp/rbf_1024_30_2_author_title/schema/rbf_1024_30_2_author_title.avsc --method RBF --dataset dblp
enc_list

