enc_encode_local_avro --avro_files  pprl-scaling-framework-shell/target/appassembler/data/random/avro --schema_file pprl-scaling-framework-shell/target/appassembler/data/random/schema/random.avsc --selected_fields random_int --rest_fields random_word --method FBF --N 500 --K 2 --Q 2 --name stat_enc_500
enc_encode_local_avro --avro_files  pprl-scaling-framework-shell/target/appassembler/data/random/avro --schema_file pprl-scaling-framework-shell/target/appassembler/data/random/schema/random.avsc --selected_fields random_int --rest_fields random_word --method FBF --K 2 --Q 2 --name dyn_enc
enc_import --avro_files stat_enc_500.avro --schema_file stat_enc_500.avsc --method FBF --dataset random
enc_import --avro_files dyn_enc.avro --schema_file dyn_enc.avsc --method FBF --dataset random
enc_encode_local_avro --avro_files  pprl-scaling-framework-shell/target/appassembler/data/da_int/avro --schema_file pprl-scaling-framework-shell/target/appassembler/data/da_int/schema/da_int.avsc --selected_fields daInteger --method FBF --N 500 --K 15 --Q 3 --name stat_enc_500
enc_encode_local_avro --avro_files  pprl-scaling-framework-shell/target/appassembler/data/da_int/avro --schema_file pprl-scaling-framework-shell/target/appassembler/data/da_int/schema/da_int.avsc --selected_fields daInteger --method FBF --K 15 --Q 3 --name dyn_enc
enc_import --avro_files stat_enc_500.avro --schema_file stat_enc_500.avsc --method FBF --dataset da_int
enc_import --avro_files dyn_enc.avro --schema_file dyn_enc.avsc --method FBF --dataset da_int
enc_list
enc_list --name random
enc_list --name da_int
enc_list --method FBF
enc_list --method FBF --name dblp
